name: fmaps
description: A simple Flutter Package to display maps form different providers
version: 0.0.1
homepage: https://github.com/Supercaly/fmaps
repository: https://github.com/Supercaly/fmaps
issue_tracker: https://github.com/Supercaly/fmaps/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/placeholder.png